spring.application.name=RateLimiter

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Rate Limit Routes — strategy must match: fixed, sliding, token
rate-limit.routes[0].path=/api/auth/login
rate-limit.routes[0].limit=5
rate-limit.routes[0].window-secs=900
rate-limit.routes[0].strategy=fixed
rate-limit.routes[0].key-prefix=auth

rate-limit.routes[1].path=/api/search
rate-limit.routes[1].limit=30
rate-limit.routes[1].window-secs=60
rate-limit.routes[1].strategy=sliding
rate-limit.routes[1].key-prefix=search

rate-limit.routes[2].path=/api/upload
rate-limit.routes[2].limit=10
rate-limit.routes[2].window-secs=3600
rate-limit.routes[2].strategy=fixed
rate-limit.routes[2].key-prefix=upload

rate-limit.routes[3].path=/api/public
rate-limit.routes[3].limit=100
rate-limit.routes[3].window-secs=60
rate-limit.routes[3].strategy=fixed
rate-limit.routes[3].key-prefix=public

rate-limit.routes[4].path=/api/user
rate-limit.routes[4].limit=10
rate-limit.routes[4].window-secs=60
rate-limit.routes[4].strategy=fixed
rate-limit.routes[4].key-prefix=user

rate-limit.routes[5].path=/api/admin
rate-limit.routes[5].limit=5
rate-limit.routes[5].window-secs=60
rate-limit.routes[5].strategy=sliding
rate-limit.routes[5].key-prefix=admin